create table books(
id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(255) not null
);

create table authors(
id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(255) not null
);

create table authors_books(
id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
book_id integer not null,
author_id integer not null,
foreign key (book_id) REFERENCES books(id),
foreign key (author_id) REFERENCES authors(id)
);