create table departments (
    id integer generated by default as identity primary key,
    name varchar(255) not null
);

create table employees (
    id integer generated by default as identity primary key,
    name varchar(255) not null,
    department_id integer,
    foreign key (department_id) references departments(id)
);

insert into departments (name) values
('HR'),
('IT'),
('Finance'),
('Marketing'),
('Operations');

insert into employees (name, department_id) values
('John Doe', NULL),
('Jane Smith', 1),
('Alice Johnson', NULL),
('Bob Brown', 2),
('Charlie Green', 3);

select * from employees e
         left join departments d on e.department_id = d.id;
select * from departments d
         right join employees e on d.id = e.department_id;
select * from employees e
         full join departments d on e.department_id = d.id;
select * from employees e
         cross join departments d;

select * from departments d
         left join employees e on e.department_id = d.id
         where e.department_id is null;

select * from employees e
         left join departments d on e.department_id = d.id;
select * from employees e
         right join departments d on d.id = e.department_id;

create table teens (
    id integer generated by default as identity primary key,
    name varchar(255) not null,
	gender varchar(255) not null
);

insert into teens (name, gender) values
('Вася', 'мужской'),
('Маша', 'женский'),
('Петя', 'мужской'),
('Катя', 'женский'),
('Саша', 'мужской'),
('Оля', 'женский'),
('Игорь', 'мужской'),
('Аня', 'женский'),
('Костя', 'мужской'),
('Лена', 'женский');

select t1.name teen1, t2.name teen2 from teens t1
                                    cross join teens t2
                                    where t1.gender != t2.gender
                                      and t1.name < t2.name;