create table car_bodies (
	id integer generated by default as identity primary key,
	name varchar(255) not null
);

create table car_engines (
	id integer generated by default as identity primary key,
	name varchar(255) not null
);

create table car_transmissions (
	id integer generated by default as identity primary key,
	name varchar(255) not null
);

create table cars (
	id integer generated by default as identity primary key,
	name varchar(255) not null,
	body_id integer,
	engine_id integer,
	transmission_id integer,
	foreign key (body_id) references car_bodies(id),
	foreign key (engine_id) references car_engines(id),
	foreign key (transmission_id) references car_transmissions(id)
);

insert into car_bodies (name) values
('Sedan'),
('Hatchback'),
('SUV'),
('Coupe'),
('Convertible');

insert into car_engines (name) values
('V6'),
('V8'),
('Electric'),
('Diesel'),
('Hybrid');

insert into car_transmissions (name) values
('Automatic'),
('Manual'),
('CVT'),
('Dual-clutch'),
('Semi-automatic');

insert into cars (name, body_id, engine_id, transmission_id) values
('Toyota Camry', 1, 1, 1),
('Ford Focus', 2, 2, 2),
('Tesla Model X', 3, 3, 1),
('Honda Civic', 2, 1, 2),
('Chevrolet Tahoe', 3, 2, 1),
('Nissan Leaf', 2, 3, 3),
('BMW 3 Series', 1, 1, 3),
('Audi Q7', 3, 2, 1),
('Porsche 911', 4, 2, 4),
('Mercedes C-Class', 1, 5, 5);

select c.id id, c.name car_name, cb.name body_name, ce.name engine_name, ct.name transmission_name
    from cars c
	left join car_bodies cb on c.body_id = cb.id
	left join car_engines ce on c.engine_id = ce.id
	left join car_transmissions ct on c.transmission_id = ct.id;

select cb.name body_name
    from car_bodies cb
    left join cars c on c.body_id = cb.id where c.body_id is null;

select ce.name engine_name
    from car_engines ce
    left join cars c on c.engine_id = ce.id where c.engine_id is null;

select ct.name transmission_name
    from car_transmissions ct
    left join cars c on c.transmission_id = ct.id where c.transmission_id is null;
